# Generated by Django 2.1.5 on 2019-02-26 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190217_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_day',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='ending time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='starting time'),
        ),
    ]
