# Generated by Django 2.1.5 on 2019-04-02 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190226_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(blank=True, default='Please describe your event.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Start Time'),
        ),
    ]
