# Generated by Django 2.1.5 on 2019-04-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='volunteer_notes',
            field=models.TextField(blank=True, default='Please leave any other information you would like us to know.', null=True, verbose_name='Notes'),
        ),
    ]
