# Generated by Django 2.1.5 on 2019-04-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_signup_volunteer_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='add_to_cal',
            field=models.BooleanField(default=False, verbose_name='Add event to my calendar?'),
        ),
    ]
