# Generated by Django 2.1.5 on 2019-04-29 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_signup_add_to_cal'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_contact_email',
            field=models.CharField(default='kpettit@nd.edu', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_contact_phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='event',
            name='event_coordinator',
            field=models.CharField(default='Kendyl Pettit', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_organization',
            field=models.CharField(default='Practice', max_length=200),
            preserve_default=False,
        ),
    ]
