# Generated by Django 2.1.5 on 2019-04-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190429_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_contact_email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
