# Generated by Django 2.1.5 on 2019-05-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190429_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='e_contact_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='e_contact_phone',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='signup',
            name='e_coordinator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='e_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='signup',
            name='e_end_time',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='signup',
            name='e_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='e_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='e_organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='e_start_time',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Start Time'),
        ),
    ]
